language: python

python:
  - 3.5.2
  - 3.6.1

install:
  - pip --version

script:
  # Tests
  - python -m unittest discover -v
  # PyLint
  - make lint

notifications:
  email:
    on_success: change
    on_failure: change
